package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/client/authentication"
	"github.com/victorock/gocoprhd/client/block"
	"github.com/victorock/gocoprhd/client/export"
	"github.com/victorock/gocoprhd/client/get"
	"github.com/victorock/gocoprhd/client/post"
	"github.com/victorock/gocoprhd/client/put"
	"github.com/victorock/gocoprhd/client/search"
	"github.com/victorock/gocoprhd/client/snapshot"
	"github.com/victorock/gocoprhd/client/task"
	"github.com/victorock/gocoprhd/client/vdc"
	"github.com/victorock/gocoprhd/client/volume"
)

// Default copr h d HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new copr h d HTTP client.
func NewHTTPClient(formats strfmt.Registry) *CoprHD {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/", []string{"http", "https"})
	return New(transport, formats)
}

// New creates a new copr h d client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *CoprHD {
	cli := new(CoprHD)
	cli.Transport = transport

	cli.Authentication = authentication.New(transport, formats)

	cli.Block = block.New(transport, formats)

	cli.Export = export.New(transport, formats)

	cli.Get = get.New(transport, formats)

	cli.Post = post.New(transport, formats)

	cli.Put = put.New(transport, formats)

	cli.Search = search.New(transport, formats)

	cli.Snapshot = snapshot.New(transport, formats)

	cli.Task = task.New(transport, formats)

	cli.Vdc = vdc.New(transport, formats)

	cli.Volume = volume.New(transport, formats)

	return cli
}

// CoprHD is a client for copr h d
type CoprHD struct {
	Authentication *authentication.Client

	Block *block.Client

	Export *export.Client

	Get *get.Client

	Post *post.Client

	Put *put.Client

	Search *search.Client

	Snapshot *snapshot.Client

	Task *task.Client

	Vdc *vdc.Client

	Volume *volume.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *CoprHD) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Authentication.SetTransport(transport)

	c.Block.SetTransport(transport)

	c.Export.SetTransport(transport)

	c.Get.SetTransport(transport)

	c.Post.SetTransport(transport)

	c.Put.SetTransport(transport)

	c.Search.SetTransport(transport)

	c.Snapshot.SetTransport(transport)

	c.Task.SetTransport(transport)

	c.Vdc.SetTransport(transport)

	c.Volume.SetTransport(transport)

}
