package snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// NewCreateSnapshotFullCopyParams creates a new CreateSnapshotFullCopyParams object
// with the default values initialized.
func NewCreateSnapshotFullCopyParams() *CreateSnapshotFullCopyParams {
	var ()
	return &CreateSnapshotFullCopyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSnapshotFullCopyParamsWithTimeout creates a new CreateSnapshotFullCopyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSnapshotFullCopyParamsWithTimeout(timeout time.Duration) *CreateSnapshotFullCopyParams {
	var ()
	return &CreateSnapshotFullCopyParams{

		timeout: timeout,
	}
}

/*CreateSnapshotFullCopyParams contains all the parameters to send to the API endpoint
for the create snapshot full copy operation typically these are written to a http.Request
*/
type CreateSnapshotFullCopyParams struct {

	/*Body*/
	Body *models.CreateSnapshotFullCopy
	/*ID
	  The URN of a ViPR/CoprHD Task

	*/
	ID string

	timeout time.Duration
}

// WithBody adds the body to the create snapshot full copy params
func (o *CreateSnapshotFullCopyParams) WithBody(Body *models.CreateSnapshotFullCopy) *CreateSnapshotFullCopyParams {
	o.Body = Body
	return o
}

// WithID adds the id to the create snapshot full copy params
func (o *CreateSnapshotFullCopyParams) WithID(ID string) *CreateSnapshotFullCopyParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSnapshotFullCopyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.CreateSnapshotFullCopy)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
