package snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewShowSnapshotParams creates a new ShowSnapshotParams object
// with the default values initialized.
func NewShowSnapshotParams() *ShowSnapshotParams {
	var ()
	return &ShowSnapshotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowSnapshotParamsWithTimeout creates a new ShowSnapshotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowSnapshotParamsWithTimeout(timeout time.Duration) *ShowSnapshotParams {
	var ()
	return &ShowSnapshotParams{

		timeout: timeout,
	}
}

/*ShowSnapshotParams contains all the parameters to send to the API endpoint
for the show snapshot operation typically these are written to a http.Request
*/
type ShowSnapshotParams struct {

	/*ID
	  The URN of a ViPR/CoprHD Snapshot

	*/
	ID string

	timeout time.Duration
}

// WithID adds the id to the show snapshot params
func (o *ShowSnapshotParams) WithID(ID string) *ShowSnapshotParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ShowSnapshotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
