package export

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteExportGroupParams creates a new DeleteExportGroupParams object
// with the default values initialized.
func NewDeleteExportGroupParams() *DeleteExportGroupParams {
	var ()
	return &DeleteExportGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteExportGroupParamsWithTimeout creates a new DeleteExportGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteExportGroupParamsWithTimeout(timeout time.Duration) *DeleteExportGroupParams {
	var ()
	return &DeleteExportGroupParams{

		timeout: timeout,
	}
}

/*DeleteExportGroupParams contains all the parameters to send to the API endpoint
for the delete export group operation typically these are written to a http.Request
*/
type DeleteExportGroupParams struct {

	/*ID
	  The URN of a ViPR/CoprHD ExportGroup

	*/
	ID string

	timeout time.Duration
}

// WithID adds the id to the delete export group params
func (o *DeleteExportGroupParams) WithID(ID string) *DeleteExportGroupParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteExportGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
