package export

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// NewUpdateExportParams creates a new UpdateExportParams object
// with the default values initialized.
func NewUpdateExportParams() *UpdateExportParams {
	var ()
	return &UpdateExportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateExportParamsWithTimeout creates a new UpdateExportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateExportParamsWithTimeout(timeout time.Duration) *UpdateExportParams {
	var ()
	return &UpdateExportParams{

		timeout: timeout,
	}
}

/*UpdateExportParams contains all the parameters to send to the API endpoint
for the update export operation typically these are written to a http.Request
*/
type UpdateExportParams struct {

	/*Body*/
	Body *models.UpdateExport
	/*ID
	  The URN of a ViPR/CoprHD ExportGroup

	*/
	ID string

	timeout time.Duration
}

// WithBody adds the body to the update export params
func (o *UpdateExportParams) WithBody(Body *models.UpdateExport) *UpdateExportParams {
	o.Body = Body
	return o
}

// WithID adds the id to the update export params
func (o *UpdateExportParams) WithID(ID string) *UpdateExportParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.UpdateExport)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
