package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// NewCreateVolumeSnapshotParams creates a new CreateVolumeSnapshotParams object
// with the default values initialized.
func NewCreateVolumeSnapshotParams() *CreateVolumeSnapshotParams {
	var ()
	return &CreateVolumeSnapshotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVolumeSnapshotParamsWithTimeout creates a new CreateVolumeSnapshotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateVolumeSnapshotParamsWithTimeout(timeout time.Duration) *CreateVolumeSnapshotParams {
	var ()
	return &CreateVolumeSnapshotParams{

		timeout: timeout,
	}
}

/*CreateVolumeSnapshotParams contains all the parameters to send to the API endpoint
for the create volume snapshot operation typically these are written to a http.Request
*/
type CreateVolumeSnapshotParams struct {

	/*Body*/
	Body *models.CreateVolumeSnapshot
	/*ID
	  The URN of a ViPR/CoprHD Volume

	*/
	ID string

	timeout time.Duration
}

// WithBody adds the body to the create volume snapshot params
func (o *CreateVolumeSnapshotParams) WithBody(Body *models.CreateVolumeSnapshot) *CreateVolumeSnapshotParams {
	o.Body = Body
	return o
}

// WithID adds the id to the create volume snapshot params
func (o *CreateVolumeSnapshotParams) WithID(ID string) *CreateVolumeSnapshotParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVolumeSnapshotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.CreateVolumeSnapshot)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
