package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// CreateVolumeFullCopyReader is a Reader for the CreateVolumeFullCopy structure.
type CreateVolumeFullCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateVolumeFullCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewCreateVolumeFullCopyAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateVolumeFullCopyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewCreateVolumeFullCopyAccepted creates a CreateVolumeFullCopyAccepted with default headers values
func NewCreateVolumeFullCopyAccepted() *CreateVolumeFullCopyAccepted {
	return &CreateVolumeFullCopyAccepted{}
}

/*CreateVolumeFullCopyAccepted handles this case with default header values.

Task Object
*/
type CreateVolumeFullCopyAccepted struct {
	Payload *models.Tasks
}

func (o *CreateVolumeFullCopyAccepted) Error() string {
	return fmt.Sprintf("[POST /block/volumes/{id}/protection/full-copies.json][%d] createVolumeFullCopyAccepted  %+v", 202, o.Payload)
}

func (o *CreateVolumeFullCopyAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Tasks)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateVolumeFullCopyDefault creates a CreateVolumeFullCopyDefault with default headers values
func NewCreateVolumeFullCopyDefault(code int) *CreateVolumeFullCopyDefault {
	return &CreateVolumeFullCopyDefault{
		_statusCode: code,
	}
}

/*CreateVolumeFullCopyDefault handles this case with default header values.

Error Message
*/
type CreateVolumeFullCopyDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create volume full copy default response
func (o *CreateVolumeFullCopyDefault) Code() int {
	return o._statusCode
}

func (o *CreateVolumeFullCopyDefault) Error() string {
	return fmt.Sprintf("[POST /block/volumes/{id}/protection/full-copies.json][%d] CreateVolumeFullCopy default  %+v", o._statusCode, o.Payload)
}

func (o *CreateVolumeFullCopyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
