package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// CreateVolumeSnapshotReader is a Reader for the CreateVolumeSnapshot structure.
type CreateVolumeSnapshotReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateVolumeSnapshotReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewCreateVolumeSnapshotAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateVolumeSnapshotDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewCreateVolumeSnapshotAccepted creates a CreateVolumeSnapshotAccepted with default headers values
func NewCreateVolumeSnapshotAccepted() *CreateVolumeSnapshotAccepted {
	return &CreateVolumeSnapshotAccepted{}
}

/*CreateVolumeSnapshotAccepted handles this case with default header values.

Task Object
*/
type CreateVolumeSnapshotAccepted struct {
	Payload *models.Task
}

func (o *CreateVolumeSnapshotAccepted) Error() string {
	return fmt.Sprintf("[POST /block/volumes/{id}/protection/snapshots.json][%d] createVolumeSnapshotAccepted  %+v", 202, o.Payload)
}

func (o *CreateVolumeSnapshotAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Task)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateVolumeSnapshotDefault creates a CreateVolumeSnapshotDefault with default headers values
func NewCreateVolumeSnapshotDefault(code int) *CreateVolumeSnapshotDefault {
	return &CreateVolumeSnapshotDefault{
		_statusCode: code,
	}
}

/*CreateVolumeSnapshotDefault handles this case with default header values.

Error Message
*/
type CreateVolumeSnapshotDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create volume snapshot default response
func (o *CreateVolumeSnapshotDefault) Code() int {
	return o._statusCode
}

func (o *CreateVolumeSnapshotDefault) Error() string {
	return fmt.Sprintf("[POST /block/volumes/{id}/protection/snapshots.json][%d] CreateVolumeSnapshot default  %+v", o._statusCode, o.Payload)
}

func (o *CreateVolumeSnapshotDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
