package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// CreateSnapshotFullCopyReader is a Reader for the CreateSnapshotFullCopy structure.
type CreateSnapshotFullCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateSnapshotFullCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewCreateSnapshotFullCopyAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateSnapshotFullCopyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewCreateSnapshotFullCopyAccepted creates a CreateSnapshotFullCopyAccepted with default headers values
func NewCreateSnapshotFullCopyAccepted() *CreateSnapshotFullCopyAccepted {
	return &CreateSnapshotFullCopyAccepted{}
}

/*CreateSnapshotFullCopyAccepted handles this case with default header values.

Task Object
*/
type CreateSnapshotFullCopyAccepted struct {
	Payload *models.Tasks
}

func (o *CreateSnapshotFullCopyAccepted) Error() string {
	return fmt.Sprintf("[POST /block/snapshots/{id}/protection/full-copies.json][%d] createSnapshotFullCopyAccepted  %+v", 202, o.Payload)
}

func (o *CreateSnapshotFullCopyAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Tasks)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSnapshotFullCopyDefault creates a CreateSnapshotFullCopyDefault with default headers values
func NewCreateSnapshotFullCopyDefault(code int) *CreateSnapshotFullCopyDefault {
	return &CreateSnapshotFullCopyDefault{
		_statusCode: code,
	}
}

/*CreateSnapshotFullCopyDefault handles this case with default header values.

Error Message
*/
type CreateSnapshotFullCopyDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create snapshot full copy default response
func (o *CreateSnapshotFullCopyDefault) Code() int {
	return o._statusCode
}

func (o *CreateSnapshotFullCopyDefault) Error() string {
	return fmt.Sprintf("[POST /block/snapshots/{id}/protection/full-copies.json][%d] CreateSnapshotFullCopy default  %+v", o._statusCode, o.Payload)
}

func (o *CreateSnapshotFullCopyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
