package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// CreateExportReader is a Reader for the CreateExport structure.
type CreateExportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateExportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateExportDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewCreateExportOK creates a CreateExportOK with default headers values
func NewCreateExportOK() *CreateExportOK {
	return &CreateExportOK{}
}

/*CreateExportOK handles this case with default header values.

Task Object
*/
type CreateExportOK struct {
	Payload *models.Task
}

func (o *CreateExportOK) Error() string {
	return fmt.Sprintf("[POST /block/exports.json][%d] createExportOK  %+v", 200, o.Payload)
}

func (o *CreateExportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Task)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateExportDefault creates a CreateExportDefault with default headers values
func NewCreateExportDefault(code int) *CreateExportDefault {
	return &CreateExportDefault{
		_statusCode: code,
	}
}

/*CreateExportDefault handles this case with default header values.

Error Message
*/
type CreateExportDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create export default response
func (o *CreateExportDefault) Code() int {
	return o._statusCode
}

func (o *CreateExportDefault) Error() string {
	return fmt.Sprintf("[POST /block/exports.json][%d] CreateExport default  %+v", o._statusCode, o.Payload)
}

func (o *CreateExportDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
