package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// DeleteExportReader is a Reader for the DeleteExport structure.
type DeleteExportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewDeleteExportAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteExportDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteExportAccepted creates a DeleteExportAccepted with default headers values
func NewDeleteExportAccepted() *DeleteExportAccepted {
	return &DeleteExportAccepted{}
}

/*DeleteExportAccepted handles this case with default header values.

Task Object
*/
type DeleteExportAccepted struct {
	Payload *models.Tasks
}

func (o *DeleteExportAccepted) Error() string {
	return fmt.Sprintf("[POST /block/exports/{id}/deactivate.json][%d] deleteExportAccepted  %+v", 202, o.Payload)
}

func (o *DeleteExportAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Tasks)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteExportDefault creates a DeleteExportDefault with default headers values
func NewDeleteExportDefault(code int) *DeleteExportDefault {
	return &DeleteExportDefault{
		_statusCode: code,
	}
}

/*DeleteExportDefault handles this case with default header values.

Error Message
*/
type DeleteExportDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete export default response
func (o *DeleteExportDefault) Code() int {
	return o._statusCode
}

func (o *DeleteExportDefault) Error() string {
	return fmt.Sprintf("[POST /block/exports/{id}/deactivate.json][%d] DeleteExport default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteExportDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
