package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// DeleteVolumeReader is a Reader for the DeleteVolume structure.
type DeleteVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewDeleteVolumeAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteVolumeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteVolumeAccepted creates a DeleteVolumeAccepted with default headers values
func NewDeleteVolumeAccepted() *DeleteVolumeAccepted {
	return &DeleteVolumeAccepted{}
}

/*DeleteVolumeAccepted handles this case with default header values.

Task Object
*/
type DeleteVolumeAccepted struct {
	Payload *models.Tasks
}

func (o *DeleteVolumeAccepted) Error() string {
	return fmt.Sprintf("[POST /block/volumes/{id}/deactivate.json][%d] deleteVolumeAccepted  %+v", 202, o.Payload)
}

func (o *DeleteVolumeAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Tasks)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteVolumeDefault creates a DeleteVolumeDefault with default headers values
func NewDeleteVolumeDefault(code int) *DeleteVolumeDefault {
	return &DeleteVolumeDefault{
		_statusCode: code,
	}
}

/*DeleteVolumeDefault handles this case with default header values.

Error Message
*/
type DeleteVolumeDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete volume default response
func (o *DeleteVolumeDefault) Code() int {
	return o._statusCode
}

func (o *DeleteVolumeDefault) Error() string {
	return fmt.Sprintf("[POST /block/volumes/{id}/deactivate.json][%d] DeleteVolume default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteVolumeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
