package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// NewExpandVolumeParams creates a new ExpandVolumeParams object
// with the default values initialized.
func NewExpandVolumeParams() *ExpandVolumeParams {
	var ()
	return &ExpandVolumeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExpandVolumeParamsWithTimeout creates a new ExpandVolumeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExpandVolumeParamsWithTimeout(timeout time.Duration) *ExpandVolumeParams {
	var ()
	return &ExpandVolumeParams{

		timeout: timeout,
	}
}

/*ExpandVolumeParams contains all the parameters to send to the API endpoint
for the expand volume operation typically these are written to a http.Request
*/
type ExpandVolumeParams struct {

	/*Body*/
	Body *models.ExpandVolume
	/*ID
	  The URN of a ViPR/CoprHD Volume

	*/
	ID string

	timeout time.Duration
}

// WithBody adds the body to the expand volume params
func (o *ExpandVolumeParams) WithBody(Body *models.ExpandVolume) *ExpandVolumeParams {
	o.Body = Body
	return o
}

// WithID adds the id to the expand volume params
func (o *ExpandVolumeParams) WithID(ID string) *ExpandVolumeParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ExpandVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.ExpandVolume)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
