package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListVolumeSnapshotsParams creates a new ListVolumeSnapshotsParams object
// with the default values initialized.
func NewListVolumeSnapshotsParams() *ListVolumeSnapshotsParams {
	var ()
	return &ListVolumeSnapshotsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListVolumeSnapshotsParamsWithTimeout creates a new ListVolumeSnapshotsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListVolumeSnapshotsParamsWithTimeout(timeout time.Duration) *ListVolumeSnapshotsParams {
	var ()
	return &ListVolumeSnapshotsParams{

		timeout: timeout,
	}
}

/*ListVolumeSnapshotsParams contains all the parameters to send to the API endpoint
for the list volume snapshots operation typically these are written to a http.Request
*/
type ListVolumeSnapshotsParams struct {

	/*ID
	  The URN of a ViPR/CoprHD Volume

	*/
	ID string

	timeout time.Duration
}

// WithID adds the id to the list volume snapshots params
func (o *ListVolumeSnapshotsParams) WithID(ID string) *ListVolumeSnapshotsParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ListVolumeSnapshotsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
