package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// ListVolumeSnapshotsReader is a Reader for the ListVolumeSnapshots structure.
type ListVolumeSnapshotsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *ListVolumeSnapshotsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListVolumeSnapshotsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewListVolumeSnapshotsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewListVolumeSnapshotsOK creates a ListVolumeSnapshotsOK with default headers values
func NewListVolumeSnapshotsOK() *ListVolumeSnapshotsOK {
	return &ListVolumeSnapshotsOK{}
}

/*ListVolumeSnapshotsOK handles this case with default header values.

List Volume Snapshot
*/
type ListVolumeSnapshotsOK struct {
	Payload *models.VolumeSnapshots
}

func (o *ListVolumeSnapshotsOK) Error() string {
	return fmt.Sprintf("[GET /block/volumes/{id}/protection/snapshots.json][%d] listVolumeSnapshotsOK  %+v", 200, o.Payload)
}

func (o *ListVolumeSnapshotsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VolumeSnapshots)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListVolumeSnapshotsDefault creates a ListVolumeSnapshotsDefault with default headers values
func NewListVolumeSnapshotsDefault(code int) *ListVolumeSnapshotsDefault {
	return &ListVolumeSnapshotsDefault{
		_statusCode: code,
	}
}

/*ListVolumeSnapshotsDefault handles this case with default header values.

Error Message
*/
type ListVolumeSnapshotsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list volume snapshots default response
func (o *ListVolumeSnapshotsDefault) Code() int {
	return o._statusCode
}

func (o *ListVolumeSnapshotsDefault) Error() string {
	return fmt.Sprintf("[GET /block/volumes/{id}/protection/snapshots.json][%d] ListVolumeSnapshots default  %+v", o._statusCode, o.Payload)
}

func (o *ListVolumeSnapshotsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
