package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListVolumeExportsParams creates a new ListVolumeExportsParams object
// with the default values initialized.
func NewListVolumeExportsParams() *ListVolumeExportsParams {
	var ()
	return &ListVolumeExportsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListVolumeExportsParamsWithTimeout creates a new ListVolumeExportsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListVolumeExportsParamsWithTimeout(timeout time.Duration) *ListVolumeExportsParams {
	var ()
	return &ListVolumeExportsParams{

		timeout: timeout,
	}
}

/*ListVolumeExportsParams contains all the parameters to send to the API endpoint
for the list volume exports operation typically these are written to a http.Request
*/
type ListVolumeExportsParams struct {

	/*ID
	  The URN of a ViPR/CoprHD Volume

	*/
	ID string

	timeout time.Duration
}

// WithID adds the id to the list volume exports params
func (o *ListVolumeExportsParams) WithID(ID string) *ListVolumeExportsParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ListVolumeExportsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
