package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// ShowVolumeExportsReader is a Reader for the ShowVolumeExports structure.
type ShowVolumeExportsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *ShowVolumeExportsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewShowVolumeExportsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewShowVolumeExportsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewShowVolumeExportsOK creates a ShowVolumeExportsOK with default headers values
func NewShowVolumeExportsOK() *ShowVolumeExportsOK {
	return &ShowVolumeExportsOK{}
}

/*ShowVolumeExportsOK handles this case with default header values.

Volume Exports
*/
type ShowVolumeExportsOK struct {
	Payload *models.VolumeExports
}

func (o *ShowVolumeExportsOK) Error() string {
	return fmt.Sprintf("[GET /block/volumes/{id}/exports.json][%d] showVolumeExportsOK  %+v", 200, o.Payload)
}

func (o *ShowVolumeExportsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VolumeExports)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowVolumeExportsDefault creates a ShowVolumeExportsDefault with default headers values
func NewShowVolumeExportsDefault(code int) *ShowVolumeExportsDefault {
	return &ShowVolumeExportsDefault{
		_statusCode: code,
	}
}

/*ShowVolumeExportsDefault handles this case with default header values.

Error Message
*/
type ShowVolumeExportsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the show volume exports default response
func (o *ShowVolumeExportsDefault) Code() int {
	return o._statusCode
}

func (o *ShowVolumeExportsDefault) Error() string {
	return fmt.Sprintf("[GET /block/volumes/{id}/exports.json][%d] ShowVolumeExports default  %+v", o._statusCode, o.Payload)
}

func (o *ShowVolumeExportsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
