package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// ShowVolumeReader is a Reader for the ShowVolume structure.
type ShowVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *ShowVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewShowVolumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewShowVolumeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewShowVolumeOK creates a ShowVolumeOK with default headers values
func NewShowVolumeOK() *ShowVolumeOK {
	return &ShowVolumeOK{}
}

/*ShowVolumeOK handles this case with default header values.

Volumes Details
*/
type ShowVolumeOK struct {
	Payload models.Volume
}

func (o *ShowVolumeOK) Error() string {
	return fmt.Sprintf("[GET /block/volumes/{id}.json][%d] showVolumeOK  %+v", 200, o.Payload)
}

func (o *ShowVolumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowVolumeDefault creates a ShowVolumeDefault with default headers values
func NewShowVolumeDefault(code int) *ShowVolumeDefault {
	return &ShowVolumeDefault{
		_statusCode: code,
	}
}

/*ShowVolumeDefault handles this case with default header values.

Error Message
*/
type ShowVolumeDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the show volume default response
func (o *ShowVolumeDefault) Code() int {
	return o._statusCode
}

func (o *ShowVolumeDefault) Error() string {
	return fmt.Sprintf("[GET /block/volumes/{id}.json][%d] ShowVolume default  %+v", o._statusCode, o.Payload)
}

func (o *ShowVolumeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
