package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewShowVolumeParams creates a new ShowVolumeParams object
// with the default values initialized.
func NewShowVolumeParams() *ShowVolumeParams {
	var ()
	return &ShowVolumeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowVolumeParamsWithTimeout creates a new ShowVolumeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowVolumeParamsWithTimeout(timeout time.Duration) *ShowVolumeParams {
	var ()
	return &ShowVolumeParams{

		timeout: timeout,
	}
}

/*ShowVolumeParams contains all the parameters to send to the API endpoint
for the show volume operation typically these are written to a http.Request
*/
type ShowVolumeParams struct {

	/*ID
	  The URN of a ViPR/CoprHD Volume

	*/
	ID string

	timeout time.Duration
}

// WithID adds the id to the show volume params
func (o *ShowVolumeParams) WithID(ID string) *ShowVolumeParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ShowVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
