package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewShowVolumeExportsParams creates a new ShowVolumeExportsParams object
// with the default values initialized.
func NewShowVolumeExportsParams() *ShowVolumeExportsParams {
	var ()
	return &ShowVolumeExportsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowVolumeExportsParamsWithTimeout creates a new ShowVolumeExportsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowVolumeExportsParamsWithTimeout(timeout time.Duration) *ShowVolumeExportsParams {
	var ()
	return &ShowVolumeExportsParams{

		timeout: timeout,
	}
}

/*ShowVolumeExportsParams contains all the parameters to send to the API endpoint
for the show volume exports operation typically these are written to a http.Request
*/
type ShowVolumeExportsParams struct {

	/*ID
	  The URN of a ViPR/CoprHD Volume

	*/
	ID string

	timeout time.Duration
}

// WithID adds the id to the show volume exports params
func (o *ShowVolumeExportsParams) WithID(ID string) *ShowVolumeExportsParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ShowVolumeExportsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
