package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteVolumeParams creates a new DeleteVolumeParams object
// with the default values initialized.
func NewDeleteVolumeParams() *DeleteVolumeParams {
	var ()
	return &DeleteVolumeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVolumeParamsWithTimeout creates a new DeleteVolumeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVolumeParamsWithTimeout(timeout time.Duration) *DeleteVolumeParams {
	var ()
	return &DeleteVolumeParams{

		timeout: timeout,
	}
}

/*DeleteVolumeParams contains all the parameters to send to the API endpoint
for the delete volume operation typically these are written to a http.Request
*/
type DeleteVolumeParams struct {

	/*ID
	  The URN of a ViPR/CoprHD Volume

	*/
	ID string

	timeout time.Duration
}

// WithID adds the id to the delete volume params
func (o *DeleteVolumeParams) WithID(ID string) *DeleteVolumeParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
