package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/victorock/gocoprhd/models"
)

// ListVolumeSearchReader is a Reader for the ListVolumeSearch structure.
type ListVolumeSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *ListVolumeSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListVolumeSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewListVolumeSearchDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewListVolumeSearchOK creates a ListVolumeSearchOK with default headers values
func NewListVolumeSearchOK() *ListVolumeSearchOK {
	return &ListVolumeSearchOK{}
}

/*ListVolumeSearchOK handles this case with default header values.

Generic Object
*/
type ListVolumeSearchOK struct {
	Payload ListVolumeSearchOKBodyBody
}

func (o *ListVolumeSearchOK) Error() string {
	return fmt.Sprintf("[GET /block/volumes/search.json?{item}={name}][%d] listVolumeSearchOK  %+v", 200, o.Payload)
}

func (o *ListVolumeSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListVolumeSearchDefault creates a ListVolumeSearchDefault with default headers values
func NewListVolumeSearchDefault(code int) *ListVolumeSearchDefault {
	return &ListVolumeSearchDefault{
		_statusCode: code,
	}
}

/*ListVolumeSearchDefault handles this case with default header values.

Error Message
*/
type ListVolumeSearchDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list volume search default response
func (o *ListVolumeSearchDefault) Code() int {
	return o._statusCode
}

func (o *ListVolumeSearchDefault) Error() string {
	return fmt.Sprintf("[GET /block/volumes/search.json?{item}={name}][%d] ListVolumeSearch default  %+v", o._statusCode, o.Payload)
}

func (o *ListVolumeSearchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ListVolumeSearchOKBodyBody list volume search o k body body

swagger:model ListVolumeSearchOKBodyBody
*/
type ListVolumeSearchOKBodyBody interface{}
