package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*CreateSnapshotFullCopy create snapshot full copy

swagger:model CreateSnapshotFullCopy
*/
type CreateSnapshotFullCopy struct {

	/* count
	 */
	Count int64 `json:"count,omitempty"`

	/* create inactive
	 */
	CreateInactive string `json:"create_inactive,omitempty"`

	/* name
	 */
	Name string `json:"name,omitempty"`

	/* type
	 */
	Type string `json:"type,omitempty"`
}

// Validate validates this create snapshot full copy
func (m *CreateSnapshotFullCopy) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
