package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*CreateVolumeSnapshot create volume snapshot

swagger:model CreateVolumeSnapshot
*/
type CreateVolumeSnapshot struct {

	/* create inactive
	 */
	CreateInactive string `json:"create_inactive,omitempty"`

	/* name
	 */
	Name string `json:"name,omitempty"`

	/* read only
	 */
	ReadOnly string `json:"read_only,omitempty"`

	/* type
	 */
	Type string `json:"type,omitempty"`
}

// Validate validates this create volume snapshot
func (m *CreateVolumeSnapshot) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
