package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*ExpandVolume expand volume

swagger:model ExpandVolume
*/
type ExpandVolume struct {

	/* new size
	 */
	NewSize string `json:"new_size,omitempty"`
}

// Validate validates this expand volume
func (m *ExpandVolume) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
