package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Task task

swagger:model Task
*/
type Task struct {
	Resource

	/* associated resources
	 */
	AssociatedResources []string `json:"associated_resources,omitempty"`

	/* creation time
	 */
	CreationTime int64 `json:"creation_time,omitempty"`

	/* description
	 */
	Description string `json:"description,omitempty"`

	/* global
	 */
	Global bool `json:"global,omitempty"`

	/* inactive
	 */
	Inactive bool `json:"inactive,omitempty"`

	/* internal
	 */
	Internal bool `json:"internal,omitempty"`

	/* message
	 */
	Message string `json:"message,omitempty"`

	/* op id
	 */
	OpID string `json:"op_id,omitempty"`

	/* progress
	 */
	Progress int64 `json:"progress,omitempty"`

	/* remote
	 */
	Remote bool `json:"remote,omitempty"`

	/* start time
	 */
	StartTime int64 `json:"start_time,omitempty"`

	/* state
	 */
	State string `json:"state,omitempty"`

	/* tags
	 */
	Tags []string `json:"tags,omitempty"`

	/* tenant
	 */
	Tenant *Resource `json:"tenant,omitempty"`

	/* vdc
	 */
	Vdc *Resource `json:"vdc,omitempty"`
}

// Validate validates this task
func (m *Task) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.Resource.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAssociatedResources(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTags(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTenant(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVdc(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Task) validateAssociatedResources(formats strfmt.Registry) error {

	return nil
}

func (m *Task) validateTags(formats strfmt.Registry) error {

	return nil
}

func (m *Task) validateTenant(formats strfmt.Registry) error {

	if m.Tenant != nil {

		if err := m.Tenant.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}

func (m *Task) validateVdc(formats strfmt.Registry) error {

	if m.Vdc != nil {

		if err := m.Vdc.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
