package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

/*Tasks tasks

swagger:model Tasks
*/
type Tasks struct {

	/* task
	 */
	Task []*Task `json:"task,omitempty"`
}

// Validate validates this tasks
func (m *Tasks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTask(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tasks) validateTask(formats strfmt.Registry) error {

	if swag.IsZero(m.Task) { // not required
		return nil
	}

	for i := 0; i < len(m.Task); i++ {

		if swag.IsZero(m.Task[i]) { // not required
			continue
		}

		if m.Task[i] != nil {

			if err := m.Task[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
