package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

/*VolumeSnapshots volume snapshots

swagger:model VolumeSnapshots
*/
type VolumeSnapshots struct {

	/* snapshot
	 */
	Snapshot []*Resource `json:"snapshot,omitempty"`
}

// Validate validates this volume snapshots
func (m *VolumeSnapshots) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSnapshot(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VolumeSnapshots) validateSnapshot(formats strfmt.Registry) error {

	if swag.IsZero(m.Snapshot) { // not required
		return nil
	}

	for i := 0; i < len(m.Snapshot); i++ {

		if swag.IsZero(m.Snapshot[i]) { // not required
			continue
		}

		if m.Snapshot[i] != nil {

			if err := m.Snapshot[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
